apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: krateo-remote-client
  name: krateo-remote-client
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: krateo-remote-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: krateo-remote-client
    spec:
      containers:
        - image: app-client
          imagePullPolicy: IfNotPresent
          name: krateo-remote-client
          env:
            - name: NODE_ID
              value: "crocodile"
            - name: REMOTE_HOST
              value: "http://krateo-remote-server.remote.svc"
          # livenessProbe:
          #   httpGet:
          #     path: /nginx_status
          #     port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          resources:
            limits:
              memory: "32Mi"
              cpu: "10m"
