apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-krateo-remote-server
config:
  origins:
    - "*"
  credentials: true
  max_age: 3600
  preflight_continue: false
plugin: cors
