apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krateo-remote-server
  annotations:
    kubernetes.io/ingress.class: kong
    plugins.konghq.com: cors-krateo-remote-server
spec:
  rules:
    - host: krateo-remote-server.krateo.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: krateo-remote-server
                port:
                  number: 80
