apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - _deployment.yaml
  - _service.yaml
  - _ingress.yaml

namespace: remote

images:
  - name: app
    newName: ghcr.io/krateoplatformops/krateo-remote-server
    newTag: 0.1.1
